In [ ]:
import numpy as np

Basic array creation

In [ ]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [ ]:
array= [1,2,3,4]
array

[1, 2, 3, 4]

Datatype of array
Arrays is made to always store only one type of data

In [ ]:
a=[1,2,3,4,5,6,7,8,"hello"]
np.array(a)



array(['1', '2', '3', '4', '5', '6', '7', '8', 'hello'], dtype='<U21')

1Dimension vectors are called as --->VECTORS,  

2Dimension arrangement is called as ---->2D arrays


In [ ]:
arr= [[1,2,3],[4,5,6]]
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6]])

Array genration function

In [ ]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

Random generation function

In [ ]:
np.random.rand(5)


array([0.92909386, 0.18693301, 0.34189781, 0.06075202, 0.55731969])

In [ ]:
np.random.randn(4)

array([ 0.01158029,  0.096035  ,  1.00197992, -2.66221425])

In [ ]:
np.random.randint(1,100,20)

array([86, 57, 46, 86, 52, 70, 86, 86, 24, 67,  7, 66, 28, 74, 80, 17, 52,
       52, 87, 40])

Array Attributes

In [ ]:
arr_2 = np.arange(1,31)
arr_2
arr_2 = arr_2.reshape(5,6)
arr_2


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr_2.shape

(5, 6)

In [ ]:
arr_2.size

30

In [ ]:
arr.dtype

dtype('int64')

Array methods

In [ ]:
arr_2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr_2.min()

np.int64(1)

In [ ]:
arr_2.max()

np.int64(30)

In [ ]:
arr_2.sum()

np.int64(465)

In [ ]:
np.sum(arr_2,axis=0)

array([65, 70, 75, 80, 85, 90])

In [ ]:
np.sum(arr_2,axis=1)

array([ 21,  57,  93, 129, 165])

In [ ]:
arr_2.mean()

np.float64(15.5)

In [ ]:
arr_2.argmax()


np.int64(29)

RESHAPING AND RESIZING OF ARRAY

In [ ]:
arr_3=np.arange(1,31)
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr_3=arr_3.reshape(6,5)
arr_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr_4=arr_3.reshape(5,6)
arr_4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])